language: python
python:
  - "3.5"

script:
  - mkdir transcode logs defaults app
  - python plextidy.py -o true

before_deploy: "echo 'ready?'"

deploy:
  provider: releases
  api_key: $GITHUB_AUTO_RELEASE_TOKEN
  file:
    - 'plextidy.py'
    - 'plextidy.cnf'
  skip_cleanup: true
  on:
    tags: true
env:
  - TRAVIS=true
git:
  depth: 3