language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"

script:
  - mkdir transcode config logs defaults app data
  - python plextidy.py

before_deploy: "echo 'ready?'"

deploy:
  provider: releases
  api_key: $GITHUB_AUTO_RELEASE_TOKEN
  file:
    - 'plextidy.py'
    - 'plextidy.cnf'
  skip_cleanup: true
  on:
    tags: true
git:
  depth: 3